import {NextRequest,NextResponse} from 'next/server';
import {db,assert,id,tx,getProject,saveProject,listProjects,budget,audit,rateLimit} from '../../../server/db.mjs';
import {user,origin,sendLink,consume} from '../../../server/auth.mjs';
import {createProject,updateScenes,approve,quote,enqueue,active,selectVideo} from '../../../server/domain.mjs';
import {catalog,voices} from '../../../server/providers.mjs';
import {storeFile,filePath,readFile,verify} from '../../../server/media.mjs';
import sharp from 'sharp';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const json=(x:unknown,status=200)=>NextResponse.json(x,{status,headers:{'Cache-Control':'no-store'}});
async function handle(req:NextRequest,ctx:{params:Promise<{path:string[]}>}){try{const {path:parts}=await ctx.params;const [route,pid,action]=parts;const method=req.method;if(method!=='GET')origin(req);
if(route==='health'&&method==='GET'){const hb=db.prepare('SELECT updated FROM heartbeat WHERE id=1').get() as any;const worker=!!hb&&Date.now()-Number(hb.updated)<180000;return json({status:worker?'ok':'starting',worker},worker?200:503);}
if(route==='auth'&&method==='POST'){const body=await req.json();if(pid==='link'){await sendLink(body.email);return json({message:'등록된 이메일이면 로그인 링크가 발송됩니다.'});}if(pid==='consume'){const session=consume(body.token);const res=json({ok:true});res.cookies.set('studio_session',session,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:86400});return res;}if(pid==='logout'){const raw=req.cookies.get('studio_session')?.value;if(raw){const {hash}=await import('../../../server/db.mjs');db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(raw));}const res=json({ok:true});res.cookies.delete('studio_session');return res;}}
if(route==='media'&&method==='GET'){const f=db.prepare('SELECT * FROM files WHERE id=?').get(pid) as any;assert(f&&f.expires>Date.now(),'파일이 만료되었거나 없습니다.',404);const project=db.prepare('SELECT deleted FROM projects WHERE id=?').get(f.project) as any;assert(project&&!project.deleted,'파일을 찾을 수 없습니다.',404);const signed=verify(pid,req.nextUrl.searchParams.get('expires')||'',req.nextUrl.searchParams.get('sig')||'');if(!signed)assert(user(req)===f.owner,'파일 접근 권한이 없습니다.',403);const buf=await readFile(filePath(pid));const headers:Record<string,string>={'Content-Type':f.mime,'Cache-Control':'private, no-store','Accept-Ranges':'bytes'};if(req.nextUrl.searchParams.has('download'))headers['Content-Disposition']='attachment; filename="shortform.mp4"';const range=req.headers.get('range');if(range){const m=/^bytes=(\d+)-(\d*)$/.exec(range);assert(m,'지원하지 않는 범위입니다.',416);const start=Number(m![1]),end=m![2]?Math.min(Number(m![2]),buf.length-1):buf.length-1;assert(start<=end&&start<buf.length,'잘못된 범위입니다.',416);headers['Content-Range']=`bytes ${start}-${end}/${buf.length}`;return new Response(buf.subarray(start,end+1),{status:206,headers});}return new Response(buf,{headers});}
const email=user(req);const owner=process.env.CLIENT_EMAIL?.trim().toLowerCase()||email;const admin=email===process.env.ADMIN_EMAIL?.trim().toLowerCase();if(route==='me')return json({email,admin});if(route==='status'){const hb=db.prepare('SELECT updated FROM heartbeat WHERE id=1').get() as any;return json({creatify:!!(process.env.CREATIFY_API_ID&&process.env.CREATIFY_API_KEY),script:!!(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL),rates:!!process.env.RATES_REVIEWED_AT,worker:!!hb&&Date.now()-Number(hb.updated)<180000});}
if(route==='catalog'&&method==='GET'){assert(rateLimit('catalog:'+email,120,60000),'잠시 후 다시 조회해 주세요.',429);return json(pid==='voices'?await voices():await catalog(Number(req.nextUrl.searchParams.get('page')||1)));}
if(route==='operations'){assert(admin,'운영 권한이 필요합니다.',403);if(method==='GET')return json({jobs:db.prepare('SELECT id,project,kind,status,reserved,actual,provider_id,error,created FROM jobs ORDER BY created DESC LIMIT 100').all(),audit:db.prepare('SELECT * FROM audit ORDER BY created DESC LIMIT 100').all()});if(method==='POST'){const b=await req.json();const j=db.prepare('SELECT * FROM jobs WHERE id=?').get(b.id) as any;assert(j&&['unknown','failed'].includes(j.status),'확인이 필요한 작업만 처리할 수 있습니다.');if(b.providerId){assert(['audio','video'].includes(j.kind)&&/^[a-f0-9-]{36}$/.test(b.providerId),'공급자 ID를 확인해 주세요.');db.prepare("UPDATE jobs SET provider_id=?,status='running',error=NULL WHERE id=?").run(b.providerId,j.id);}else{assert(Number.isInteger(b.actual)&&b.actual>=0&&b.confirmed===true,'실제 과금 확인이 필요합니다.');db.prepare("UPDATE jobs SET actual=?,status='failed',error='운영자 정산 완료' WHERE id=?").run(b.actual,j.id);}audit(email,'job.reconcile',j.project);return json({ok:true});}}
if(route==='projects'){if(!pid&&method==='GET')return json({projects:listProjects(owner),budget:budget(owner,'')});if(!pid&&method==='POST')return json(createProject(owner,await req.json()),201);const p=getProject(pid,owner);if(method==='GET')return json({project:p,budget:budget(owner,pid),jobs:db.prepare('SELECT id,kind,scene,status,reserved,actual,error,created FROM jobs WHERE project=? ORDER BY created DESC LIMIT 30').all(pid)});if(method==='DELETE'){assert(!active(p),'진행 중인 작업을 먼저 확인해 주세요.');db.prepare('UPDATE projects SET deleted=1 WHERE id=?').run(pid);audit(email,'project.delete',pid);return json({ok:true});}
if(action==='upload'){assert(!active(p),'작업 완료 후 업로드해 주세요.');assert(p.assets.length<10,'이미지는 최대 10개입니다.');assert(Number(req.headers.get('content-length')||0)<11*1024*1024,'파일은 10MB 이하만 가능합니다.');const form=await req.formData();const f=form.get('file');assert(f instanceof File&&f.size<=10*1024*1024,'파일은 10MB 이하만 가능합니다.');const file=f as File;const image=sharp(Buffer.from(await file.arrayBuffer()),{limitInputPixels:40000000});const meta=await image.metadata();assert(['jpeg','png','webp'].includes(meta.format||''),'JPEG·PNG·WebP만 업로드할 수 있습니다.');const buf=await image.rotate().resize(1600,1600,{fit:'inside',withoutEnlargement:true}).webp().toBuffer();const asset=await storeFile(pid,owner,buf,'image/webp','product.webp');tx(()=>{const current=getProject(pid,owner);assert(!active(current)&&current.assets.length<10,'프로젝트 상태가 변경되었습니다.');current.assets.push(asset);current.revision++;saveProject(current);});return json(asset);}
const b=await req.json();if(action==='select-video')return json(selectVideo(owner,pid,b.scene,b.file));if(action==='scenes')return json(updateScenes(owner,pid,b.revision,b.scenes));if(action==='approve')return json(approve(owner,pid,b.scene,b.stage));if(action==='quote')return json(quote(owner,pid,b.kind,b.scene));if(action==='generate'){assert(b.confirmed===true,'비용 확인이 필요합니다.');return json(enqueue(owner,pid,b.quote,b.idempotencyKey),202);}if(action==='settings'){return json(tx(()=>{const current=getProject(pid,owner);assert(!active(current),'진행 중인 작업을 먼저 확인해 주세요.');assert(['none','ambient'].includes(b.bgm)&&typeof b.volume==='number'&&b.volume>=0&&b.volume<=.4,'잘못된 배경음 설정입니다.');current.bgm=b.bgm;current.bgmVolume=b.volume;current.revision++;saveProject(current);return current;}));}}
return json({error:'경로를 찾을 수 없습니다.'},404);
}catch(e:any){return json({error:e.name==='ZodError'?'입력값을 확인해 주세요.':e.message||'요청에 실패했습니다.'},e.status||400);}}
export const GET=handle;export const POST=handle;export const DELETE=handle;
