'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,LoaderCircle} from 'lucide-react';

type Mode='login'|'signup'|'find-id'|'forgot'|'verify'|'reset';

async function post(path:string,body:Record<string,string>){const response=await fetch('/api/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'요청을 완료하지 못했습니다.');return data;}

export default function AuthPortal(){
 const [mode,setMode]=useState<Mode>('login'),[token,setToken]=useState(''),[identifier,setIdentifier]=useState(''),[accountId,setAccountId]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const params=new URLSearchParams(location.search);const requested=params.get('mode');const incoming=params.get('token')||'';if((requested==='verify'||requested==='reset')&&incoming){setMode(requested);setToken(incoming);history.replaceState(null,'','/login?mode='+requested);}},[]);
 async function run(fn:()=>Promise<any>,done?:(data:any)=>void){setBusy(true);setError('');setMessage('');try{const data=await fn();if(done)done(data);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function choose(next:Mode){setMode(next);setError('');setMessage('');setPassword('');setConfirm('');}
 const title=mode==='login'?'다시, 이야기를 만들 시간.':mode==='signup'?'새 스튜디오 계정 만들기':mode==='find-id'?'아이디 찾기':mode==='forgot'?'비밀번호 찾기':mode==='verify'?'이메일 인증 완료하기':'새 비밀번호 설정';
 const description=mode==='login'?'아이디 또는 이메일과 비밀번호로 로그인하세요.':mode==='signup'?'이메일 인증 후 바로 스튜디오를 사용할 수 있습니다.':mode==='find-id'?'가입할 때 사용한 이메일로 아이디를 보내드립니다.':mode==='forgot'?'아이디 또는 이메일로 재설정 링크를 보내드립니다.':mode==='verify'?'아래 버튼을 누르면 가입이 완료되고 로그인됩니다.':'영문과 숫자를 포함해 10자 이상 입력해 주세요.';
 return <main className="login auth-page"><div className="brand">f<span>frame</span></div><div className="auth-card"><div className="eyebrow">YOUR PRIVATE SHORTFORM STUDIO</div><h1>{title}</h1><p>{description}</p>
 {mode==='login'&&<form onSubmit={e=>{e.preventDefault();run(()=>post('login',{identifier,password}),()=>location.href='/');}}><label>아이디 또는 이메일<input required autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="아이디 또는 you@company.com"/></label><label>비밀번호<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="비밀번호"/></label><button disabled={busy} className="primary">로그인 <ArrowRight size={17}/></button><div className="auth-links"><button type="button" onClick={()=>choose('find-id')}>아이디 찾기</button><button type="button" onClick={()=>choose('forgot')}>비밀번호 찾기</button><button type="button" onClick={()=>choose('signup')}>회원가입</button></div></form>}
 {mode==='signup'&&<form onSubmit={e=>{e.preventDefault();if(password!==confirm){setError('비밀번호 확인이 일치하지 않습니다.');return;}run(()=>post('register',{id:accountId,email,password}),d=>setMessage(d.message));}}><label>아이디<input required minLength={4} maxLength={40} autoComplete="username" value={accountId} onChange={e=>setAccountId(e.target.value.toLowerCase())} placeholder="영문 소문자와 숫자 4~40자"/></label><label>이메일<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>비밀번호<input required minLength={10} maxLength={128} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="영문·숫자 포함 10자 이상"/></label><label>비밀번호 확인<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="비밀번호 다시 입력"/></label><button disabled={busy||!!message} className="primary">인증 이메일 받고 가입하기 <ArrowRight size={17}/></button></form>}
 {mode==='find-id'&&<form onSubmit={e=>{e.preventDefault();run(()=>post('find-id',{email}),d=>setMessage(d.message));}}><label>가입 이메일<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><button disabled={busy} className="primary">아이디 안내 메일 받기 <ArrowRight size={17}/></button></form>}
 {mode==='forgot'&&<form onSubmit={e=>{e.preventDefault();run(()=>post('forgot-password',{identifier}),d=>setMessage(d.message));}}><label>아이디 또는 이메일<input required autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="아이디 또는 you@company.com"/></label><button disabled={busy} className="primary">비밀번호 재설정 메일 받기 <ArrowRight size={17}/></button></form>}
 {mode==='verify'&&<button disabled={busy||!token} className="primary auth-submit" onClick={()=>run(()=>post('verify',{token}),()=>location.href='/')}>이메일 인증하고 시작하기 <ArrowRight size={17}/></button>}
 {mode==='reset'&&<form onSubmit={e=>{e.preventDefault();if(password!==confirm){setError('비밀번호 확인이 일치하지 않습니다.');return;}run(()=>post('reset-password',{token,password}),()=>location.href='/');}}><label>새 비밀번호<input required minLength={10} maxLength={128} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="영문·숫자 포함 10자 이상"/></label><label>새 비밀번호 확인<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="비밀번호 다시 입력"/></label><button disabled={busy||!token} className="primary">비밀번호 변경하고 로그인 <ArrowRight size={17}/></button></form>}
 {busy&&<p className="auth-progress"><LoaderCircle className="spin" size={16}/>처리하고 있어요.</p>}{message&&<p role="status" className="notice success">{message}</p>}{error&&<p role="alert" className="notice error">{error}</p>}
 {mode!=='login'&&<button className="auth-back" type="button" onClick={()=>choose('login')}><ArrowLeft size={15}/>로그인으로 돌아가기</button>}</div><a className="preview-link" href="/preview">계정 없이 제작 화면 미리보기 <ArrowUpRight size={15}/></a><small>계정별 프로젝트와 생성 기록은 서로 분리됩니다.</small></main>;
}
