'use client';
import {useEffect,useState} from 'react';
type Obj=Record<string,any>;
const labels:Record<string,string>={title:'프로젝트 이름',description:'상품 정보와 이야기 · AI 요약 초안',audience:'누구에게 전하나요? · AI 제안',facts:'원본 기재 정보 · 진위 검증 아님',cta:'마지막 메시지 · AI 제안'};
async function api(path:string,body?:Obj){const r=await fetch('/api/detail-drafts'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'요청에 실패했습니다.');return d;}
export default function DetailImport({brief,onApply,onDraft,initialDraft=null,preview=false}:{brief:Obj,onApply:(v:Obj)=>void,onDraft:(d:Obj|null)=>void,initialDraft?:Obj|null,preview?:boolean}){
 const [draft,setDraft]=useState<Obj|null>(initialDraft),[recent,setRecent]=useState<Obj[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(false),[quote,setQuote]=useState<Obj|null>(null),[product,setProduct]=useState(0),[values,setValues]=useState<Obj>({}),[selected,setSelected]=useState<Obj>({}),[source,setSource]=useState(0),[rights,setRights]=useState(false);
 function update(d:Obj){setDraft(d);onDraft(d);}
 async function task(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{if(initialDraft&&!preview)api('/'+initialDraft.id).then(update).catch((e:Error)=>setError(e.message));if(!preview)api('').then(d=>setRecent(d.drafts.filter((x:Obj)=>x.images.length))).catch(()=>{});},[preview]);
 const running=!!draft?.job&&['queued','running','submitting'].includes(draft.job.status),blocked=running||draft?.job?.status==='unknown';
 useEffect(()=>{if(!draft||!running)return;const t=setInterval(()=>{api('/'+draft.id).then(update).catch((e:Error)=>setError(e.message));},2500);return()=>clearInterval(t);},[draft?.id,running]);
 function choose(index:number){const p=draft!.result.products[index];setProduct(index);setValues({title:p.title,description:p.description,audience:p.audience,cta:p.cta,facts:p.claims.filter((c:Obj)=>c.status==='source').map((c:Obj)=>c.text+' [출처 '+c.sources.join(', ')+']').join('\n')});setSelected({title:true,description:true,audience:true,facts:true,cta:true});setSource(0);}
 function openReview(){choose(0);setReview(true);}
 async function upload(files:File[]){if(!files?.length)return;if(preview)throw Error('미리보기에서는 분석을 실행하지 않습니다. 로그인 후 사용해 주세요.');if((draft?.images.length||0)+files.length>10)throw Error('이미지는 최대 10장입니다.');let d=draft||await api('',{});update(d);for(const file of Array.from(files)){const form=new FormData();form.set('file',file);const r=await fetch('/api/detail-drafts/'+d.id+'/upload',{method:'POST',body:form});const out=await r.json();if(!r.ok)throw Error(out.error);d=out;update(d);}}
 async function reorder(ids:string[]){update(await api('/'+draft!.id+'/images',{revision:draft!.revision,ids}));}
 const sources=draft?.result?.sources||[],current=sources[source];
 return <section className="detail-import">
  <h3>상품 상세페이지로 간편하게 시작하기</h3><p>이미지를 분석해 상품 정보와 광고 초안을 제안합니다. 직접 입력해도 됩니다.</p>
  {!draft&&recent.length>0&&<label>이전 임시 자료 이어서 작업<select defaultValue="" onChange={e=>{const d=recent.find(x=>x.id===e.target.value);if(d)update(d);}}><option value="">선택하세요</option>{recent.map(d=><option value={d.id} key={d.id}>{d.images[0]?.name} · {d.images.length}장</option>)}</select></label>}
  <label className="check"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>자료 사용 권한을 확인했으며 분석 시 AI 서비스로 전달하는 데 동의합니다.</label>
  <label>상세페이지 이미지 추가<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||blocked||!rights} onChange={e=>{const files=Array.from(e.target.files||[]);task(()=>upload(files));e.target.value='';}}/></label>
  <small>최대 10장 · 장당 10MB · 전체 분석 영역 최대 32개. 임시 자료는 7일 보관됩니다.</small>
  <div className="detail-thumbnails">{draft?.images.map((f:Obj,i:number)=><div key={f.id}><img src={f.url} alt={`상세페이지 ${i+1}`}/><span>{i+1}. {f.name}</span><div><button type="button" disabled={busy||blocked||i===0} aria-label={`이미지 ${i+1} 앞으로`} onClick={()=>task(async()=>{const ids=draft.images.map((x:Obj)=>x.id);[ids[i-1],ids[i]]=[ids[i],ids[i-1]];await reorder(ids);})}>←</button><button type="button" disabled={busy||blocked} aria-label={`이미지 ${i+1} 삭제`} onClick={()=>task(()=>reorder(draft.images.filter((x:Obj)=>x.id!==f.id).map((x:Obj)=>x.id)))}>삭제</button></div></div>)}</div>
  <div className="detail-actions"><button type="button" disabled={busy||blocked||!rights||!draft?.images.length} onClick={()=>task(async()=>setQuote({...await api('/'+draft!.id+'/quote',{}),idem:crypto.randomUUID()}))}>{draft?.result?'다시 분석하기':'분석하고 초안 만들기'}</button>{draft?.result?.products.length>0&&<button type="button" onClick={openReview}>분석 결과 검토</button>}{draft&&<button type="button" disabled={busy||blocked} onClick={()=>{setDraft(null);onDraft(null);setReview(false);setQuote(null);}}>새 자료로 시작</button>}</div>
  {busy&&<p role="status">처리하고 있습니다. 업로드한 자료는 유지됩니다.</p>}{running&&<p role="status">이미지를 분석하고 있습니다. 창을 닫아도 작업은 계속됩니다.</p>}
  {draft?.job?.status==='unknown'&&<p role="alert">분석 결과 확인이 필요합니다. 중복 과금을 막기 위해 운영자가 기존 요청을 확인한 뒤 재시도할 수 있습니다.</p>}
  {draft?.job?.status==='failed'&&<p role="alert">{draft.job.error||'분석에 실패했습니다. 자료를 확인한 후 다시 시도해 주세요.'}</p>}
  {draft?.result?.warnings.map((w:string,i:number)=><p className="detail-warning" key={i}>{w}</p>)}
  {draft?.result&&!draft.result.products.length&&<p>상품 정보를 읽지 못했습니다. 글씨가 선명한 이미지를 추가해 주세요.</p>}
  {error&&<p role="alert" className="detail-warning">{error}</p>}
  {quote&&<div className="detail-quote"><strong>예상 예약 비용 ₩{quote.amount.toLocaleString('ko-KR')}</strong><p>{quote.tiles}개 영역 분석 · 실제 사용량으로 정산합니다. 프로젝트를 만들지 않아도 월간 비용에 포함됩니다.</p><p>이번 달 사용·예약 ₩{quote.budget.month.toLocaleString('ko-KR')} / 100,000</p><button type="button" disabled={busy} onClick={()=>task(async()=>{await api('/'+draft!.id+'/analyze',{quote,idem:quote.idem,confirmed:true});update(await api('/'+draft!.id));setQuote(null);})}>비용 확인하고 분석</button><button type="button" onClick={()=>setQuote(null)}>취소</button></div>}
  {review&&draft?.result&&<div className="detail-review" role="dialog" aria-modal="true" aria-label="상세페이지 분석 결과 검토">
   <header><h2>원본과 분석 결과 검토</h2><button type="button" onClick={()=>setReview(false)}>검토 닫기</button></header>
   <div className="detail-review-grid"><div className="detail-source"><label>원본 출처<select value={source} onChange={e=>setSource(Number(e.target.value))}>{sources.map((s:Obj,i:number)=><option key={i} value={i}>출처 {i+1} · {s.name} · 세로 {s.top}px</option>)}</select></label>{current&&<><div className="detail-crop" style={{aspectRatio:`${current.width}/${current.height}`}}><img alt={`출처 ${source+1} 분석 영역`} src={current.url} style={{width:`${draft.images.find((i:Obj)=>i.id===current.image).width/current.width*100}%`,left:`${-current.left/current.width*100}%`,top:`${-current.top/current.height*100}%`}}/></div><a href={current.url} target="_blank" rel="noreferrer">원본 전체 보기</a></>}</div>
   <div className="detail-fields"><label>광고에 사용할 상품·옵션<select value={product} onChange={e=>choose(Number(e.target.value))}>{draft.result.products.map((p:Obj,i:number)=><option key={i} value={i}>{p.name}</option>)}</select></label>
    <p>상품이 여러 개라면 하나를 선택하세요. AI 제안은 원본의 사실과 다릅니다. 기존 내용은 적용 전까지 유지됩니다.</p>
    <h3>추출한 상품 정보</h3>{draft.result.products[product].claims.map((c:Obj,i:number)=><div className="detail-claim" key={i}><strong>{c.status==='source'?'원본 기재':'확인 필요'}</strong><p>{c.text}</p>{c.sources.map((n:number)=><button type="button" key={n} onClick={()=>setSource(n-1)}>출처 {n}</button>)}{c.status==='review'&&<button type="button" onClick={()=>{if(confirm('원본과 광고 사용 적절성을 확인하셨나요? 확인한 문구를 근거란에 추가합니다.'))setValues({...values,facts:values.facts+'\n'+c.text+' [사용자 확인 · 출처 '+c.sources.join(', ')+']'});}}>확인 후 근거에 추가</button>}</div>)}
    {Object.entries(labels).map(([key,label])=><div key={key}><label className="check"><input type="checkbox" checked={!!selected[key]} onChange={e=>setSelected({...selected,[key]:e.target.checked})}/>{label}</label>{brief[key]&&<p className="detail-existing">현재 입력: {brief[key]}</p>}<textarea aria-label={label+' 제안 내용'} maxLength={key==='title'?100:key==='audience'?300:key==='cta'?120:6000} value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}/></div>)}
   </div></div><footer><button type="button" onClick={()=>setReview(false)}>닫기</button><button type="button" className="primary" disabled={busy||!Object.values(selected).some(Boolean)} onClick={()=>task(async()=>{const fields=Object.fromEntries(Object.keys(labels).filter(k=>selected[k]).map(k=>[k,values[k]||'']));if(Object.keys(fields).some(k=>brief[k]&&brief[k]!==fields[k])&&!confirm('선택한 입력란의 기존 내용을 검토한 내용으로 바꿀까요?'))return;update(await api('/'+draft.id+'/review',{revision:draft.revision,review:{product,fields}}));onApply(fields);setReview(false);})}>선택한 내용으로 입력란 채우기</button></footer>
  </div>}
 </section>;
}

