import {randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {db,hash,assert,tx,rateLimit,audit} from './db.mjs';
import {mailReady,sendMail} from './mail.mjs';

const SESSION_MS=7*86400000;
const TOKEN_MS=30*60000;
const emailOf=value=>String(value||'').trim().toLowerCase();
const idOf=value=>String(value||'').trim().toLowerCase();

function validEmail(email){return email.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);}
function validatePassword(password){assert(typeof password==='string'&&password.length>=10&&password.length<=128&&/[A-Za-z]/.test(password)&&/\d/.test(password),'비밀번호는 영문과 숫자를 포함해 10자 이상 입력해 주세요.');}
function registrationAllowed(email){if(process.env.ALLOW_PUBLIC_SIGNUP==='true')return true;return [process.env.CLIENT_EMAIL,process.env.ADMIN_EMAIL,...String(process.env.ALLOWED_EMAILS||'').split(',')].map(emailOf).filter(Boolean).includes(email);}

export function passwordHash(password){validatePassword(password);const salt=randomBytes(16).toString('hex');const key=scryptSync(password,salt,64,{N:16384,r:8,p:1,maxmem:64*1024*1024});return `scrypt$16384$8$1$${salt}$${key.toString('hex')}`;}
export function passwordMatches(password,encoded){try{const [kind,n,r,p,salt,stored]=String(encoded).split('$');if(kind!=='scrypt'||!stored)return false;const key=scryptSync(String(password),salt,Buffer.from(stored,'hex').length,{N:Number(n),r:Number(r),p:Number(p),maxmem:64*1024*1024});return timingSafeEqual(key,Buffer.from(stored,'hex'));}catch{return false;}}

function session(email){const raw=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(raw),email,Date.now()+SESSION_MS);return raw;}
async function issue(email,kind,mode,subject,intro){const raw=randomBytes(32).toString('hex');const key=hash(raw);db.prepare('DELETE FROM auth_tokens WHERE email=? AND kind=?').run(email,kind);db.prepare('INSERT INTO auth_tokens VALUES(?,?,?,?)').run(key,email,kind,Date.now()+TOKEN_MS);const url=new URL('/login',process.env.APP_URL);url.searchParams.set('mode',mode);url.searchParams.set('token',raw);try{await sendMail(email,subject,`${intro}\n\n${url}\n\n이 링크는 30분 동안 한 번만 사용할 수 있습니다.`);}catch(error){db.prepare('DELETE FROM auth_tokens WHERE hash=?').run(key);throw error;}}

export function user(req){const raw=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('studio_session='))?.slice(15);const account=raw?db.prepare('SELECT a.email,a.id FROM sessions s JOIN accounts a ON a.email=s.email WHERE s.hash=? AND s.expires>? AND a.verified=1').get(hash(raw),Date.now()):null;assert(account,'로그인이 필요합니다.',401);return account.email;}
export function origin(req){assert(process.env.APP_URL,'서비스 주소 설정이 필요합니다.',503);assert(req.headers.get('origin')===new URL(process.env.APP_URL).origin,'허용되지 않은 요청입니다.',403);}

export async function register(input){mailReady();const accountId=idOf(input?.id),email=emailOf(input?.email),password=String(input?.password||'');assert(/^[a-z0-9._-]{4,40}$/.test(accountId),'아이디는 영문 소문자, 숫자, 점, 밑줄, 하이픈으로 4~40자 입력해 주세요.');assert(validEmail(email),'이메일을 확인해 주세요.');assert(registrationAllowed(email),'현재 초대된 이메일만 가입할 수 있습니다.',403);const encoded=passwordHash(password);assert(rateLimit('signup:'+hash(email),3,3600000)&&rateLimit('signup:global',30,3600000),'요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.',429);const existing=db.prepare('SELECT * FROM accounts WHERE id=? OR email=?').get(accountId,email);assert(!existing||(!existing.verified&&existing.id===accountId&&existing.email===email),'이미 사용 중인 아이디 또는 이메일입니다.',409);if(existing)db.prepare('UPDATE accounts SET password=?,updated=? WHERE email=?').run(encoded,Date.now(),email);else db.prepare('INSERT INTO accounts VALUES(?,?,?,?,?,?)').run(accountId,email,encoded,0,Date.now(),Date.now());await issue(email,'verify','verify','Frame 회원가입 이메일 인증','아래 링크에서 이메일 인증을 완료해 주세요.');audit(email,'account.register');}

export function verifyRegistration(token){assert(typeof token==='string'&&token.length<200,'유효하지 않은 인증 링크입니다.');return tx(()=>{const row=db.prepare("SELECT * FROM auth_tokens WHERE hash=? AND kind='verify' AND expires>?").get(hash(token),Date.now());assert(row,'인증 링크가 만료되었거나 이미 사용되었습니다.',401);db.prepare('UPDATE accounts SET verified=1,updated=? WHERE email=?').run(Date.now(),row.email);db.prepare('DELETE FROM auth_tokens WHERE hash=?').run(hash(token));const raw=session(row.email);audit(row.email,'account.verify');return raw;});}

export function login(identifier,password){const value=idOf(identifier);assert(value&&typeof password==='string','아이디와 비밀번호를 입력해 주세요.');const permitted=rateLimit('login:'+hash(value),10,900000)&&rateLimit('login:global',100,900000);const account=db.prepare('SELECT * FROM accounts WHERE (id=? OR email=?) AND verified=1').get(value,value);const dummy='scrypt$16384$8$1$00000000000000000000000000000000$'+Buffer.alloc(64).toString('hex');const matches=passwordMatches(password,account?.password||dummy);assert(permitted&&account&&matches,'아이디 또는 비밀번호가 올바르지 않습니다.',401);const raw=session(account.email);audit(account.email,'login');return raw;}

export async function findId(email){email=emailOf(email);assert(validEmail(email),'이메일을 확인해 주세요.');const permitted=rateLimit('find-id:'+hash(email),3,3600000)&&rateLimit('account-mail:global',30,3600000);const account=db.prepare('SELECT id,email FROM accounts WHERE email=? AND verified=1').get(email);if(permitted&&account)await sendMail(email,'Frame 아이디 안내',`회원님의 Frame 아이디는 ${account.id} 입니다.\n이메일 주소로도 로그인할 수 있습니다.`);}

export async function requestPasswordReset(identifier){const value=idOf(identifier);assert(value.length<=254&&value.length>=4,'아이디 또는 이메일을 확인해 주세요.');const permitted=rateLimit('reset:'+hash(value),3,3600000)&&rateLimit('account-mail:global',30,3600000);const account=db.prepare('SELECT email FROM accounts WHERE (id=? OR email=?) AND verified=1').get(value,value);if(permitted&&account)await issue(account.email,'reset','reset','Frame 비밀번호 재설정','아래 링크에서 새 비밀번호를 설정해 주세요.');}

export function resetPassword(token,password){assert(typeof token==='string'&&token.length<200,'유효하지 않은 재설정 링크입니다.');const encoded=passwordHash(password);return tx(()=>{const row=db.prepare("SELECT * FROM auth_tokens WHERE hash=? AND kind='reset' AND expires>?").get(hash(token),Date.now());assert(row,'재설정 링크가 만료되었거나 이미 사용되었습니다.',401);db.prepare('UPDATE accounts SET password=?,updated=? WHERE email=?').run(encoded,Date.now(),row.email);db.prepare('DELETE FROM auth_tokens WHERE email=?').run(row.email);db.prepare('DELETE FROM sessions WHERE email=?').run(row.email);const raw=session(row.email);audit(row.email,'password.reset');return raw;});}
