import {db,tx,id,getProject,saveProject,assert,audit} from './db.mjs';
import {generateImage,generateSpeech,startVideo,getInteraction,interactionOutput,downloadGemini,generateScript} from './providers.mjs';
import {storeFile,cleanup} from './media.mjs';
import {duration,merge} from './render.mjs';
import {sceneSchema} from './domain.mjs';
const update=(jid,values)=>{const entries=Object.entries({...values,updated:Date.now()});db.prepare(`UPDATE jobs SET ${entries.map(([k])=>k+'=?').join(',')} WHERE id=?`).run(...entries.map(([,v])=>v),jid);};
function finish(job,results,cost,status='done'){tx(()=>{const p=getProject(job.project,job.owner);if(job.kind==='script'){p.scenes=results.map(s=>({...s,id:id(),revision:1,avatar:'',voice:'',asset:p.assets[0]?.id||'',scriptApproved:false,imageApproved:false,audioApproved:false,videoApproved:false,image:null,audio:null,video:null,history:[]}));}else if(job.kind==='merge'){p.finals.unshift({...results[0],revision:p.revision});}else for(const item of results){const s=p.scenes.find(s=>s.id===item.scene);assert(s&&s.revision===item.revision,'씬 버전이 달라 결과를 적용하지 못했습니다.');if(job.kind==='image'){s.image=item;s.imageApproved=false;if(s.video)s.history=[...(s.history||[]),{...s.video,sceneRevision:s.revision}];s.video=null;s.videoApproved=false;}else if(job.kind==='audio'){if(s.video)s.history=[...(s.history||[]),{...s.video,sceneRevision:s.revision}];s.audio=item;s.audioApproved=false;s.videoApproved=false;s.video=null;}else{if(s.video)s.history=[...(s.history||[]),{...s.video,sceneRevision:s.revision}];s.video=item;s.videoApproved=false;}}p.revision++;saveProject(p);update(job.id,{status,result:JSON.stringify(results),actual:cost===null?null:Math.ceil(cost),provider_id:status==='done'?null:job.provider_id,error:null});audit('worker','done.'+job.kind,job.project);});}
const cost=(input,kind,seconds=0)=>kind==='image'?Math.ceil(input.rates.imageUsd*input.rates.fx):kind==='audio'?Math.ceil(seconds/60*input.rates.ttsUsdPerMinute*input.rates.fx):Math.ceil(seconds*input.rates.videoUsdPerSecond*input.rates.fx);
async function step(job){const input=JSON.parse(job.input),saved=JSON.parse(job.result||'[]');if(job.kind==='script'){update(job.id,{status:'submitting'});const r=await generateScript(input.project);assert(Array.isArray(r.scenes)&&r.scenes.length>=3&&r.scenes.length<=8,'잘못된 대본 결과입니다.');const target=input.project.brief.cta?27:30;let total=0;const scenes=r.scenes.map((s,i)=>{const seconds=i===r.scenes.length-1?target-total:Math.round(target/r.scenes.length*10)/10;total+=seconds;return sceneSchema.parse({...s,seconds,id:id(),avatar:'',voice:'',asset:''});});finish(job,scenes,r.cost);return;}
if(job.kind==='merge'){update(job.id,{status:'running'});const buf=await merge(input.project);const f=await storeFile(job.project,job.owner,buf,'video/mp4','shortform.mp4');finish(job,[f],0);return;}
const s=input.selected[saved.length];if(!s){finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));return;}
if(job.kind==='image'){update(job.id,{status:'submitting'});const out=await generateImage(input.project,s);const f=await storeFile(job.project,job.owner,await downloadGemini(out),out.mime_type||'image/png','scene.png');saved.push({...f,scene:s.id,revision:s.revision,cost:cost(input,'image'),providerId:null});update(job.id,{result:JSON.stringify(saved),status:'queued'});if(saved.length===input.selected.length)finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));return;}
if(job.kind==='audio'){update(job.id,{status:'submitting'});const out=await generateSpeech(s);const f=await storeFile(job.project,job.owner,out.data,'audio/wav','voice.wav');const seconds=await duration(f.id);saved.push({...f,scene:s.id,revision:s.revision,duration:seconds,cost:cost(input,'audio',seconds),providerId:null});update(job.id,{result:JSON.stringify(saved),status:'queued'});if(saved.length===input.selected.length)finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));return;}
let pid=job.provider_id;if(!pid){update(job.id,{status:'submitting'});const r=await startVideo(input.project,s);assert(typeof r.id==='string'&&/^v1_[A-Za-z0-9_-]+$/.test(r.id),'Gemini 영상 작업 ID가 없습니다.');update(job.id,{provider_id:r.id,status:'running'});return;}
const r=await getInteraction(pid);if(['failed','cancelled'].includes(r.status)){if(saved.length)finish(job,saved,null,'failed');update(job.id,{status:'failed',error:'Gemini 영상 생성에 실패했습니다. 운영자가 과금 여부를 확인해야 합니다.'});return;}if(r.status!=='completed')return;const out=interactionOutput(r,'video');const f=await storeFile(job.project,job.owner,await downloadGemini(out),out.mime_type||'video/mp4','scene.mp4');const seconds=await duration(f.id);saved.push({...f,scene:s.id,revision:s.revision,duration:seconds,cost:cost(input,'video',seconds),providerId:pid});update(job.id,{result:JSON.stringify(saved),provider_id:null,status:'queued'});if(saved.length===input.selected.length)finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));}

let stop=false;process.on('SIGTERM',()=>stop=true);process.on('SIGINT',()=>stop=true);
const workerId=id(),leaseMs=180000,staleHeartbeatMs=30000;let waiting=false;
while(!stop){const acquired=tx(()=>{const now=Date.now(),lock=db.prepare('SELECT * FROM worker_lock WHERE id=1').get(),heartbeat=db.prepare('SELECT updated FROM heartbeat WHERE id=1').get();if(lock&&lock.expires>now&&heartbeat&&now-Number(heartbeat.updated)<staleHeartbeatMs)return false;db.prepare('INSERT OR REPLACE INTO worker_lock VALUES(1,?,?)').run(workerId,now+leaseMs);return true;});if(acquired)break;if(!waiting){console.log('Waiting for the active worker lease.');waiting=true;}await new Promise(r=>setTimeout(r,2000));}
if(stop){db.close();process.exit(0);}
const lease=setInterval(()=>{db.prepare('UPDATE worker_lock SET expires=? WHERE id=1 AND owner=?').run(Date.now()+leaseMs,workerId);db.prepare('INSERT OR REPLACE INTO heartbeat VALUES(1,?)').run(Date.now());},10000);
process.on('exit',()=>{clearInterval(lease);db.prepare('DELETE FROM worker_lock WHERE owner=?').run(workerId);});
db.prepare("UPDATE jobs SET status='unknown',error='작업 프로세스가 요청 도중 종료되었습니다. 공급자 작업을 확인해 주세요.' WHERE status='submitting'").run();
console.log('Shortform worker started.');
while(!stop){db.prepare('INSERT OR REPLACE INTO heartbeat VALUES(1,?)').run(Date.now());const job=tx(()=>db.prepare("SELECT * FROM jobs WHERE status IN ('queued','running') ORDER BY created LIMIT 1").get());if(job){try{await step(job);}catch(e){const fresh=db.prepare('SELECT * FROM jobs WHERE id=?').get(job.id);const unknown=fresh.status==='submitting';const partial=JSON.parse(fresh.result||'[]');if(partial.length&&['image','audio','video'].includes(fresh.kind))finish(fresh,partial,null,unknown?'unknown':'failed');update(job.id,{status:unknown?'unknown':'failed',error:unknown?'요청 결과가 불명확합니다. 자동 재요청하지 않으며 운영 확인이 필요합니다.':String(e.message).slice(0,300)});}}await cleanup().catch(()=>{});await new Promise(r=>setTimeout(r,process.env.NODE_ENV==='test'?Number(process.env.WORKER_POLL_MS||50):(job?5000:2000)));}
clearInterval(lease);
