import {db,tx,id,getProject,saveProject,assert,audit} from './db.mjs';
import {creatify,generateScript} from './providers.mjs';
import {storeFile,download,signedUrl,cleanup} from './media.mjs';
import {duration,merge} from './render.mjs';
import {sceneSchema} from './domain.mjs';
const update=(jid,values)=>{const entries=Object.entries({...values,updated:Date.now()});db.prepare(`UPDATE jobs SET ${entries.map(([k])=>k+'=?').join(',')} WHERE id=?`).run(...entries.map(([,v])=>v),jid);};
function finish(job,results,cost,status='done'){tx(()=>{const p=getProject(job.project,job.owner);if(job.kind==='script'){p.scenes=results.map(s=>({...s,id:id(),revision:1,avatar:'',voice:'',asset:p.assets[0]?.id||'',scriptApproved:false,audioApproved:false,videoApproved:false,audio:null,video:null,history:[]}));}else if(job.kind==='merge'){p.finals.unshift({...results[0],revision:p.revision});}else for(const item of results){const s=p.scenes.find(s=>s.id===item.scene);assert(s&&s.revision===item.revision,'씬 버전이 달라 결과를 적용하지 못했습니다.');if(job.kind==='audio'){if(s.video)s.history=[...(s.history||[]),{...s.video,sceneRevision:s.revision}];s.revision++;s.audio={...item,revision:s.revision};s.audioApproved=false;s.videoApproved=false;s.video=null;}else{if(s.video)s.history=[...(s.history||[]),{...s.video,sceneRevision:s.revision}];s.video=item;s.videoApproved=false;}}p.revision++;saveProject(p);update(job.id,{status,result:JSON.stringify(results),actual:cost===null?null:Math.ceil(cost),provider_id:status==='done'?null:job.provider_id,error:null});audit('worker','done.'+job.kind,job.project);});}
async function step(job){const input=JSON.parse(job.input),saved=JSON.parse(job.result||'[]');if(job.kind==='script'){update(job.id,{status:'submitting'});const r=await generateScript(input.project);assert(Array.isArray(r.scenes)&&r.scenes.length>=3&&r.scenes.length<=8,'잘못된 대본 결과입니다.');const target=input.project.brief.cta?27:30;let total=0;const scenes=r.scenes.map((s,i)=>{const seconds=i===r.scenes.length-1?target-total:Math.round(target/r.scenes.length*10)/10;total+=seconds;return sceneSchema.parse({...s,seconds,id:id(),avatar:'',voice:'',asset:''});});finish(job,scenes,r.cost);return;}
if(job.kind==='merge'){update(job.id,{status:'running'});const buf=await merge(input.project);const f=await storeFile(job.project,job.owner,buf,'video/mp4','shortform.mp4');finish(job,[f],0);return;}
const s=input.selected[saved.length];if(!s){finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));return;}const endpoint=job.kind==='audio'?'text_to_speech/':'lipsyncs/';let pid=job.provider_id;
if(!pid){update(job.id,{status:'submitting'});const body=job.kind==='audio'?{script:s.narration,accent:s.voice}:{name:`${job.id}:${s.id}`,creator:s.avatar,audio:signedUrl(s.audio.id),aspect_ratio:'9x16',model_version:input.model,no_caption:true,no_music:true};const r=await creatify(endpoint,body);assert(typeof r.id==='string'&&/^[a-f0-9-]{36}$/.test(r.id),'공급자 작업 ID가 없습니다.');pid=r.id;update(job.id,{provider_id:pid,status:'running'});return;}
const r=await creatify(`${endpoint}${pid}/`);if(r.status==='failed'){if(saved.length)finish(job,saved,null,'failed');update(job.id,{status:'failed',error:'공급자 생성 실패. 운영자가 과금 여부를 확인해야 합니다.'});return;}if(r.status!=='done')return;assert(r.output,'공급자 결과 파일이 없습니다.');const f=await storeFile(job.project,job.owner,await download(r.output),job.kind==='audio'?'audio/mpeg':'video/mp4',job.kind==='audio'?'voice.mp3':'scene.mp4');const seconds=await duration(f.id);assert(Number.isFinite(r.credits_used)&&r.credits_used>=0,'실제 크레딧 확인이 필요합니다.');saved.push({...f,scene:s.id,revision:s.revision,duration:seconds,cost:Math.ceil(r.credits_used*input.rates.credit),providerId:pid});update(job.id,{result:JSON.stringify(saved),provider_id:null,status:'queued'});if(saved.length===input.selected.length)finish(job,saved,saved.reduce((n,x)=>n+x.cost,0));}
let stop=false;process.on('SIGTERM',()=>stop=true);process.on('SIGINT',()=>stop=true);
const workerId=id();let waiting=false;
while(!stop){const acquired=tx(()=>{const now=Date.now();const lock=db.prepare('SELECT * FROM worker_lock WHERE id=1').get();const heartbeat=db.prepare('SELECT updated FROM heartbeat WHERE id=1').get();if(lock&&lock.expires>=now&&heartbeat&&now-Number(heartbeat.updated)<30000)return false;db.prepare('INSERT OR REPLACE INTO worker_lock VALUES(1,?,?)').run(workerId,now+180000);return true;});if(acquired)break;if(!waiting){console.log('Waiting for the active worker lease.');waiting=true;}await new Promise(r=>setTimeout(r,2000));}
if(stop){db.close();process.exit(0);}
const lease=setInterval(()=>{db.prepare('UPDATE worker_lock SET expires=? WHERE id=1 AND owner=?').run(Date.now()+180000,workerId);db.prepare('INSERT OR REPLACE INTO heartbeat VALUES(1,?)').run(Date.now());},10000);
process.on('exit',()=>{clearInterval(lease);db.prepare('DELETE FROM worker_lock WHERE owner=?').run(workerId);});
db.prepare("UPDATE jobs SET status='unknown',error='작업 프로세스가 요청 도중 종료되었습니다. 공급자 작업을 확인해 주세요.' WHERE status='submitting'").run();
console.log('Shortform worker started.');
while(!stop){db.prepare('INSERT OR REPLACE INTO heartbeat VALUES(1,?)').run(Date.now());const job=tx(()=>{const j=db.prepare("SELECT * FROM jobs WHERE status IN ('queued','running') ORDER BY created LIMIT 1").get();return j;});if(job){try{await step(job);}catch(e){const fresh=db.prepare('SELECT * FROM jobs WHERE id=?').get(job.id);const unknown=fresh.status==='submitting';const partial=JSON.parse(fresh.result||'[]');if(partial.length&&['audio','video'].includes(fresh.kind))finish(fresh,partial,null,unknown?'unknown':'failed');update(job.id,{status:unknown?'unknown':'failed',error:unknown?'요청 결과가 불명확합니다. 자동 재요청하지 않으며 운영 확인이 필요합니다.':String(e.message).slice(0,300)});}}await cleanup().catch(()=>{});await new Promise(r=>setTimeout(r,process.env.NODE_ENV==='test'?Number(process.env.WORKER_POLL_MS||50):(job?5000:2000)));}

clearInterval(lease);
